### PR TITLE
1.19.3 (Help needed)

### PR DESCRIPTION
**Pull request by TGODiamond**
(Remember to merge #51)

Add support for 1.19.3

This PR is NOT ready to be merged, since buttons aren't getting removed in the game menu and settings menu

I've observed, that Screens.getButtons in afterGameMenuScreenInit() in ScreenMixin.java isn't returning what it should:

1.19.2 (What it should return): 
screenshot

1.19.3:
screenshot2

The same is also happening in OptionsScreenMixin.java

Point is, where are the buttons now?

Weirdly, the title menu is fine and buttons are removed there

I don't know what causes that behavior, and I can't fix it

Also, I found another bug where if you enable the ".minecraft" button in the game menu, the "Mods" button disappears

### CODE REVIEW

**Comment by TGODiamond** [comment]
Maybe it's a conflict with the Mod Menu mod

**Comment by TomB-134** [comment]
Alright I'm finally looking into this and it's a disaster lol. Mojang massively changed how the pause screen buttons are handled and it's causing a lot of extra difficulty. The way Mod menu handled it has caused issues with my implementation. I'm way too tired to look more into any of this right now but I have basic button hiding working in the pause screen again. 

Thanks for your help getting the mod this far. :D

**Comment by TomB-134** [comment]
Alright I've gotten the hiding to work completely again. The only issue now is mod menu not playing nice at all.

**Comment by TGODiamond** [comment]
The game will not crash if you remove the ", remap = false" in 
@Inject(method = "add(Lnet/minecraft/client/gui/widget/ClickableWidget;ILnet/minecraft/client/gui/widget/Positioner;)Lnet/minecraft/client/gui/widget/ClickableWidget;", at = @At("HEAD"), cancellable = true, remap = false).

It will be this instead:
@Inject(method = "add(Lnet/minecraft/client/gui/widget/ClickableWidget;ILnet/minecraft/client/gui/widget/Positioner;)Lnet/minecraft/client/gui/widget/ClickableWidget;", at = @At("HEAD"), cancellable = true)

Two problems now: LAN and reporting buttons clip with the exit button, and the Online button in the settings menu not getting removed.

**Pull request merged**
